version: 2.1
commands:
   install_deps:
     steps:
       - run:
           name: Install Dependencies
           command: |
              npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
         name: Run Tests
         command: |
           npm test
  pack:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
         name: compiles
         command: |
           npm pack .
           mkdir /home/circleci/project/dist
           mv *.tgz /home/circleci/project/dist
      - store_artifacts:
         path: dist

workflows:
  build-and-package:
    jobs:
      - build
      - pack:
          requires:
            - build
          filters:
            branches:
              only: master
